apiVersion: v1
data:
  COHERE_API_KEY:
  GRAFANA_ADMIN_PASSWORD:
  OPENAI_API_KEY:
  POSTGRES_EXPORTER_PASSWORD:
  POSTGRES_PASSWORD:
  AZURE_OPENAI_API_KEY:
  AZURE_OPENAI_ENDPOINT:
  LANGCHAIN_API_KEY:
kind: Secret
metadata:
  creationTimestamp: null
  name: rag-secrets
